repos:
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--safe, --quiet, --target-version, py35]
        language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: local
    hooks:
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG.rst|HOWTORELEASE.rst|README.rst|changelog/.*)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
        language_version: python3.7
